### ISSUE TITLE
throws error if the dijit widget are loaded in a seperate frame :(

### ISSUE THREAD

**Issue by sktguha** [davidjgoss/inspector-clouseau#2]
![image](https://cloud.githubusercontent.com/assets/8387608/12067712/bbbbc412-b024-11e5-9957-6331176a5189.png)

**Comment by davidjgoss** [comment]
Hi @sktguha 

Frames are [supported](https://github.com/davidjgoss/inspector-clouseau/commit/3514b0b8052fd4d6a834a295f2fe3d957cb6116b), but looks like the problem you have there is that your frame's source is on a different origin (i.e. not `localhost`).

The little script that goes and gets the widget object and returns it to DevTools is dropped into the parent window and then checks its child frames (although not recursively) for Dijit instances. Since browsers guard against a parent window's scripts accessing the contents of a cross-origin frame, our little script is stopped in its tracks, and this is the error we see. Unfortunately I don't think there is a way around this; unlike normal Chrome extensions, DevTools extensions can only directly run code in the parent window.

However, I'm going to keep this open and labelled as a bug, as I do need to handle this sort of error more gracefully (it's far from unique to you, I'm sure) and get this limitation documented.

**Comment by sktguha** [comment]
ah I see. thanks for responding so fast :). btw I was wondering then if a message could be passed to the background page with the id of the current tab , which can do tab.injectScript with allFrames as true and hence return the dijit.byId data to the devtools js via the sendResponse. Actually I just read this https://developer.chrome.com/extensions/devtools#injecting

Also apologies if you already know about this, but if sendResponse is called async then true needs to be returned, else sendResponse becomes invalid, http://stackoverflow.com/questions/20077487/chrome-extension-message-passing-response-not-sent

**Comment by davidjgoss** [comment]
That looks worth investigating, thanks. I have a feeling, though, that the messages you pass back and forth between the window and the DevTools extension have to be JSON-compatible objects, which would rule out Dijit widgets, but we'll see.

**Comment by sktguha** [comment]
Ah I see. hmm I tried doing a djijt.byId. I could stringify it. I suppose as long as it an object then it should not be an issue. But I guess cyclical structures can still cause issue (specifically dom nodes)
However https://github.com/douglascrockford/JSON-js is also a good option for stringifying cyclic objects. I haven't used it actually yet

JSON.stringify(dijit.byId('dijit_DialogUnderlay_0'))
"{"_toConnect":{},"_attachPoints":["node"],"_attachEvents":[],"srcNodeRef":null,"_connects":[],"_supportingWidgets":[],"params":{"dialogId":"widgets_Dialog_1","class":"popupContainer_underlay"},"dialogId":"widgets_Dialog_3","class":"HistoryDetailsPopup_underlay","id":"dijit_DialogUnderlay_0","domNode":{},"_inherited":{"p":5},"node":{},"_created":true,"_focused":false,"focused":false,"_hasBeenBlurred":true,"bgIframe":{}}"

**Comment by sktguha** [comment]
Oh nice extra info is added after four years 😂
